[package]
name = "exchange-matching-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
serde = {version = "1.0.225", features = ["derive"]}
uuid = { version = "1.18.1", features = ["v4"] }